import crypto from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { config } from './config';

export const prisma = new PrismaClient();

export const ensureDatabaseSchema = async () => {
  const statements = [
    `CREATE TABLE IF NOT EXISTS "AdminUser" (
      "id" TEXT NOT NULL,
      "username" TEXT NOT NULL,
      "passwordHash" TEXT NOT NULL,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "AdminSession" (
      "id" TEXT NOT NULL,
      "token" TEXT NOT NULL,
      "expiresAt" TIMESTAMP(3) NOT NULL,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      "adminUserId" TEXT NOT NULL,
      CONSTRAINT "AdminSession_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "Asset" (
      "id" TEXT NOT NULL,
      "key" TEXT NOT NULL,
      "url" TEXT NOT NULL,
      "mimeType" TEXT NOT NULL,
      "size" INTEGER NOT NULL,
      "originalName" TEXT NOT NULL,
      "altAr" TEXT,
      "altEn" TEXT,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "Asset_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "HeroSlide" (
      "id" TEXT NOT NULL,
      "badgeAr" TEXT NOT NULL,
      "badgeEn" TEXT NOT NULL,
      "badgeIcon" TEXT NOT NULL,
      "titleArLine1" TEXT NOT NULL,
      "titleEnLine1" TEXT NOT NULL,
      "titleArLine2" TEXT NOT NULL,
      "titleEnLine2" TEXT NOT NULL,
      "descriptionAr" TEXT NOT NULL,
      "descriptionEn" TEXT NOT NULL,
      "ctaTextAr" TEXT NOT NULL,
      "ctaTextEn" TEXT NOT NULL,
      "actionType" TEXT NOT NULL,
      "actionParam" TEXT,
      "image" TEXT NOT NULL,
      "imageAltAr" TEXT NOT NULL,
      "imageAltEn" TEXT NOT NULL,
      "highlightBox" JSONB,
      "order" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "HeroSlide_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "SiteSettings" (
      "id" TEXT NOT NULL,
      "logoImageUrl" TEXT NOT NULL DEFAULT '',
      "logoImageAltAr" TEXT NOT NULL DEFAULT 'شعار شركة هشام حسن حنبولي الدولية',
      "logoImageAltEn" TEXT NOT NULL DEFAULT 'Hesham H. Hanboly International logo',
      "footerLogoImageUrl" TEXT NOT NULL DEFAULT '',
      "footerLogoImageAltAr" TEXT NOT NULL DEFAULT 'شعار التذييل لشركة هشام حسن حنبولي الدولية',
      "footerLogoImageAltEn" TEXT NOT NULL DEFAULT 'Hesham H. Hanboly International footer logo',
      "navbarCtaAr" TEXT NOT NULL,
      "navbarCtaEn" TEXT NOT NULL,
      "doctorShieldBadgeAr" TEXT NOT NULL,
      "doctorShieldBadgeEn" TEXT NOT NULL,
      "doctorShieldTitleAr" TEXT NOT NULL,
      "doctorShieldTitleEn" TEXT NOT NULL,
      "doctorShieldSubtitleAr" TEXT NOT NULL,
      "doctorShieldSubtitleEn" TEXT NOT NULL,
      "doctorShieldDescAr" TEXT NOT NULL,
      "doctorShieldDescEn" TEXT NOT NULL,
      "doctorShieldBullet1Ar" TEXT NOT NULL,
      "doctorShieldBullet1En" TEXT NOT NULL,
      "doctorShieldBullet2Ar" TEXT NOT NULL,
      "doctorShieldBullet2En" TEXT NOT NULL,
      "doctorShieldBullet3Ar" TEXT NOT NULL,
      "doctorShieldBullet3En" TEXT NOT NULL,
      "doctorShieldBullet4Ar" TEXT NOT NULL,
      "doctorShieldBullet4En" TEXT NOT NULL,
      "doctorShieldButtonAr" TEXT NOT NULL,
      "doctorShieldButtonEn" TEXT NOT NULL,
      "doctorShieldCircleTitleAr" TEXT NOT NULL,
      "doctorShieldCircleTitleEn" TEXT NOT NULL,
      "doctorShieldCirclePriceAr" TEXT NOT NULL,
      "doctorShieldCirclePriceEn" TEXT NOT NULL,
      "doctorShieldCircleNoteAr" TEXT NOT NULL,
      "doctorShieldCircleNoteEn" TEXT NOT NULL,
      "aboutSectionBadgeAr" TEXT NOT NULL,
      "aboutSectionBadgeEn" TEXT NOT NULL,
      "aboutSectionTitleAr" TEXT NOT NULL,
      "aboutSectionTitleEn" TEXT NOT NULL,
      "aboutSectionDescAr" TEXT NOT NULL,
      "aboutSectionDescEn" TEXT NOT NULL,
      "aboutSectionCardTitleAr" TEXT NOT NULL,
      "aboutSectionCardTitleEn" TEXT NOT NULL,
      "aboutSectionCardDescAr" TEXT NOT NULL,
      "aboutSectionCardDescEn" TEXT NOT NULL,
      "aboutSectionButtonAr" TEXT NOT NULL,
      "aboutSectionButtonEn" TEXT NOT NULL,
      "statisticsBadgeAr" TEXT NOT NULL,
      "statisticsBadgeEn" TEXT NOT NULL,
      "statisticsNumber" TEXT NOT NULL,
      "statisticsTitleAr" TEXT NOT NULL,
      "statisticsTitleEn" TEXT NOT NULL,
      "statisticsDescAr" TEXT NOT NULL,
      "statisticsDescEn" TEXT NOT NULL,
      "statisticsSupportAr" TEXT NOT NULL,
      "statisticsSupportEn" TEXT NOT NULL,
      "teamSectionBadgeAr" TEXT NOT NULL,
      "teamSectionBadgeEn" TEXT NOT NULL,
      "teamSectionTitleAr" TEXT NOT NULL,
      "teamSectionTitleEn" TEXT NOT NULL,
      "teamSectionDescAr" TEXT NOT NULL,
      "teamSectionDescEn" TEXT NOT NULL,
      "teamFounderBadgeAr" TEXT NOT NULL,
      "teamFounderBadgeEn" TEXT NOT NULL,
      "teamFounderNameAr" TEXT NOT NULL,
      "teamFounderNameEn" TEXT NOT NULL,
      "teamFounderRoleAr" TEXT NOT NULL,
      "teamFounderRoleEn" TEXT NOT NULL,
      "teamFounderIntroAr" TEXT NOT NULL,
      "teamFounderIntroEn" TEXT NOT NULL,
      "teamFounderImageUrl" TEXT NOT NULL,
      "teamFounderImageAltAr" TEXT NOT NULL,
      "teamFounderImageAltEn" TEXT NOT NULL,
      "teamSectionCtaAr" TEXT NOT NULL,
      "teamSectionCtaEn" TEXT NOT NULL,
      "contactSectionBadgeAr" TEXT NOT NULL,
      "contactSectionBadgeEn" TEXT NOT NULL,
      "contactSectionTitleAr" TEXT NOT NULL,
      "contactSectionTitleEn" TEXT NOT NULL,
      "contactSectionDescAr" TEXT NOT NULL,
      "contactSectionDescEn" TEXT NOT NULL,
      "contactSectionOfficeTitleAr" TEXT NOT NULL,
      "contactSectionOfficeTitleEn" TEXT NOT NULL,
      "contactSectionAddressHeadAr" TEXT NOT NULL,
      "contactSectionAddressHeadEn" TEXT NOT NULL,
      "contactSectionPhoneLabelAr" TEXT NOT NULL,
      "contactSectionPhoneLabelEn" TEXT NOT NULL,
      "contactSectionEmailLabelAr" TEXT NOT NULL,
      "contactSectionEmailLabelEn" TEXT NOT NULL,
      "contactSectionSecurityAr" TEXT NOT NULL,
      "contactSectionSecurityEn" TEXT NOT NULL,
      "contactSectionFormTitleAr" TEXT NOT NULL,
      "contactSectionFormTitleEn" TEXT NOT NULL,
      "contactSectionFormDescAr" TEXT NOT NULL,
      "contactSectionFormDescEn" TEXT NOT NULL,
      "aboutHeroBadgeAr" TEXT NOT NULL,
      "aboutHeroBadgeEn" TEXT NOT NULL,
      "aboutHeroTitleAr" TEXT NOT NULL,
      "aboutHeroTitleEn" TEXT NOT NULL,
      "aboutHeroDescAr" TEXT NOT NULL,
      "aboutHeroDescEn" TEXT NOT NULL,
      "teamHeroBadgeAr" TEXT NOT NULL,
      "teamHeroBadgeEn" TEXT NOT NULL,
      "teamHeroTitleAr" TEXT NOT NULL,
      "teamHeroTitleEn" TEXT NOT NULL,
      "teamHeroDescAr" TEXT NOT NULL,
      "teamHeroDescEn" TEXT NOT NULL,
      "contactHeroBadgeAr" TEXT NOT NULL,
      "contactHeroBadgeEn" TEXT NOT NULL,
      "contactHeroTitleAr" TEXT NOT NULL,
      "contactHeroTitleEn" TEXT NOT NULL,
      "contactHeroDescAr" TEXT NOT NULL,
      "contactHeroDescEn" TEXT NOT NULL,
      "footerDescriptionAr" TEXT NOT NULL,
      "footerDescriptionEn" TEXT NOT NULL,
      "addressAr" TEXT NOT NULL,
      "addressEn" TEXT NOT NULL,
      "email" TEXT NOT NULL,
      "phone" TEXT NOT NULL,
      "copyrightAr" TEXT NOT NULL,
      "copyrightEn" TEXT NOT NULL,
      "footerBadgeAr" TEXT NOT NULL,
      "footerBadgeEn" TEXT NOT NULL,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id")
    )`,
    `ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "logoImageUrl" TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "logoImageAltAr" TEXT NOT NULL DEFAULT 'شعار شركة هشام حسن حنبولي الدولية'`,
    `ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "logoImageAltEn" TEXT NOT NULL DEFAULT 'Hesham H. Hanboly International logo'`,
    `CREATE TABLE IF NOT EXISTS "Article" (
      "id" TEXT NOT NULL,
      "slug" TEXT NOT NULL,
      "titleAr" TEXT NOT NULL,
      "titleEn" TEXT NOT NULL,
      "excerptAr" TEXT NOT NULL,
      "excerptEn" TEXT NOT NULL,
      "categoryAr" TEXT NOT NULL,
      "categoryEn" TEXT NOT NULL,
      "authorAr" TEXT NOT NULL,
      "authorEn" TEXT NOT NULL,
      "date" TEXT NOT NULL,
      "readTimeAr" TEXT NOT NULL,
      "readTimeEn" TEXT NOT NULL,
      "bodyAr" TEXT NOT NULL,
      "bodyEn" TEXT NOT NULL,
      "imageUrl" TEXT NOT NULL,
      "published" BOOLEAN NOT NULL DEFAULT true,
      "order" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "PracticeArea" (
      "id" TEXT NOT NULL,
      "slug" TEXT NOT NULL,
      "categorySlug" TEXT NOT NULL,
      "titleAr" TEXT NOT NULL,
      "titleEn" TEXT NOT NULL,
      "categoryAr" TEXT NOT NULL,
      "categoryEn" TEXT NOT NULL,
      "shortDescAr" TEXT NOT NULL,
      "shortDescEn" TEXT NOT NULL,
      "aboutAr" JSONB NOT NULL,
      "aboutEn" JSONB NOT NULL,
      "features" JSONB NOT NULL,
      "processSteps" JSONB NOT NULL,
      "useCases" JSONB NOT NULL,
      "faq" JSONB NOT NULL,
      "imageUrl" TEXT,
      "published" BOOLEAN NOT NULL DEFAULT true,
      "order" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "PracticeArea_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "CmsPage" (
      "id" TEXT NOT NULL,
      "titleAr" TEXT NOT NULL,
      "titleEn" TEXT NOT NULL,
      "slug" TEXT NOT NULL,
      "status" TEXT NOT NULL,
      "navVisible" BOOLEAN NOT NULL DEFAULT false,
      "blocksCount" INTEGER NOT NULL DEFAULT 0,
      "author" TEXT NOT NULL,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "CmsPage_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "NavItem" (
      "id" TEXT NOT NULL,
      "pageId" TEXT NOT NULL,
      "labelAr" TEXT NOT NULL,
      "labelEn" TEXT NOT NULL,
      "url" TEXT NOT NULL,
      "desktopVisible" BOOLEAN NOT NULL DEFAULT true,
      "mobileVisible" BOOLEAN NOT NULL DEFAULT true,
      "order" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "NavItem_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE TABLE IF NOT EXISTS "CmsRevision" (
      "id" TEXT NOT NULL,
      "pageId" TEXT NOT NULL,
      "label" TEXT NOT NULL,
      "status" TEXT NOT NULL,
      "blocks" JSONB NOT NULL,
      "author" TEXT NOT NULL,
      "note" TEXT NOT NULL,
      "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP(3) NOT NULL,
      CONSTRAINT "CmsRevision_pkey" PRIMARY KEY ("id")
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "AdminUser_username_key" ON "AdminUser"("username")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "AdminSession_token_key" ON "AdminSession"("token")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "Asset_key_key" ON "Asset"("key")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "HeroSlide_id_key" ON "HeroSlide"("id")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "SiteSettings_id_key" ON "SiteSettings"("id")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "Article_slug_key" ON "Article"("slug")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "PracticeArea_slug_key" ON "PracticeArea"("slug")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "CmsPage_slug_key" ON "CmsPage"("slug")`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "NavItem_pageId_key" ON "NavItem"("pageId")`,
    `CREATE INDEX IF NOT EXISTS "CmsRevision_pageId_idx" ON "CmsRevision"("pageId")`,
  ];

  statements.push(`
    ALTER TABLE "SiteSettings"
      ADD COLUMN IF NOT EXISTS "aboutSectionBadgeAr" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionBadgeEn" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionCardTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionCardTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionCardDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionCardDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionButtonAr" TEXT,
      ADD COLUMN IF NOT EXISTS "aboutSectionButtonEn" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsBadgeAr" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsBadgeEn" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsNumber" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsSupportAr" TEXT,
      ADD COLUMN IF NOT EXISTS "statisticsSupportEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionBadgeAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionBadgeEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderBadgeAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderBadgeEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderNameAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderNameEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderRoleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderRoleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderIntroAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderIntroEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderImageUrl" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderImageAltAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamFounderImageAltEn" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionCtaAr" TEXT,
      ADD COLUMN IF NOT EXISTS "teamSectionCtaEn" TEXT,
      ADD COLUMN IF NOT EXISTS "footerLogoImageUrl" TEXT NOT NULL DEFAULT '',
      ADD COLUMN IF NOT EXISTS "footerLogoImageAltAr" TEXT NOT NULL DEFAULT 'شعار التذييل لشركة هشام حسن حنبولي الدولية',
      ADD COLUMN IF NOT EXISTS "footerLogoImageAltEn" TEXT NOT NULL DEFAULT 'Hesham H. Hanboly International footer logo',
      ADD COLUMN IF NOT EXISTS "contactSectionBadgeAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionBadgeEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionOfficeTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionOfficeTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionAddressHeadAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionAddressHeadEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionPhoneLabelAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionPhoneLabelEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionEmailLabelAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionEmailLabelEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionSecurityAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionSecurityEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionFormTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionFormTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionFormDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "contactSectionFormDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBadgeAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBadgeEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldSubtitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldSubtitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldDescAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldDescEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet1Ar" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet1En" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet2Ar" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet2En" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet3Ar" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet3En" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet4Ar" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldBullet4En" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldButtonAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldButtonEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldCircleTitleAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldCircleTitleEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldCirclePriceAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldCirclePriceEn" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldCircleNoteAr" TEXT,
      ADD COLUMN IF NOT EXISTS "doctorShieldCircleNoteEn" TEXT;
  `);

  statements.push(`
    UPDATE "SiteSettings"
    SET
      "teamFounderImageUrl" = COALESCE("teamFounderImageUrl", '/src/assets/images/founder_hesham_hanboly_1780491593879.png'),
      "teamFounderImageAltAr" = COALESCE("teamFounderImageAltAr", 'المحامي / هشام بن حسن حنبولي'),
      "teamFounderImageAltEn" = COALESCE("teamFounderImageAltEn", 'Advocate / Hesham H. Hanboly');
  `);

  for (const statement of statements) {
    await prisma.$executeRawUnsafe(statement);
  }
};

const hashPassword = (password: string) => {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(password, salt, 64).toString('hex');
  return `scrypt:${salt}:${hash}`;
};

export const verifyPassword = (password: string, storedHash: string) => {
  const [scheme, salt, hash] = storedHash.split(':');
  if (scheme !== 'scrypt' || !salt || !hash) {
    return false;
  }

  const candidate = crypto.scryptSync(password, salt, 64).toString('hex');
  return crypto.timingSafeEqual(Buffer.from(candidate, 'hex'), Buffer.from(hash, 'hex'));
};

export const ensureAdminUser = async () => {
  const existing = await prisma.adminUser.findFirst({ orderBy: { createdAt: 'asc' } });
  const passwordHash = hashPassword(config.adminPassword);

  if (!existing) {
    await prisma.adminUser.create({
      data: {
        username: config.adminUsername,
        passwordHash,
      },
    });
    return;
  }

  if (existing.username !== config.adminUsername) {
    await prisma.adminUser.update({
      where: { id: existing.id },
      data: {
        username: config.adminUsername,
        passwordHash,
      },
    });
    return;
  }

  if (!existing.passwordHash.startsWith('scrypt:')) {
    await prisma.adminUser.update({
      where: { id: existing.id },
      data: { passwordHash },
    });
  }
};

export const createPasswordHash = hashPassword;
