import { articlesData, heroSlidesData } from '../data';
import { getServicePageData, rawServices } from '../data/servicesData';
import type { ArticleRecord, HeroSlideRecord, PracticeAreaRecord, SiteContent, SiteSettingsRecord } from '../types';

const normalizeMarkdown = (value: string) => value.trim().replace(/\n{3,}/g, '\n\n');

const seedArticles = (): ArticleRecord[] =>
  articlesData
    .map((article, index) => ({
      id: article.id,
      slug: article.id,
      titleAr: article.titleAr,
      titleEn: article.titleEn,
      excerptAr: article.excerptAr,
      excerptEn: article.excerptEn,
      categoryAr: article.categoryAr,
      categoryEn: article.categoryEn,
      authorAr: article.authorAr,
      authorEn: article.authorEn,
      date: article.date,
      readTimeAr: article.readTimeAr,
      readTimeEn: article.readTimeEn,
      image: article.image,
      bodyAr: normalizeMarkdown(article.contentAr),
      bodyEn: normalizeMarkdown(article.contentEn),
      published: true,
      order: index + 1,
    }))
    .sort((left, right) => left.order - right.order);

const seedPracticeAreas = (): PracticeAreaRecord[] =>
  rawServices
    .map((service, index) => {
      const pageData = getServicePageData(service.slug);
      return {
        id: `practice-${service.slug}`,
        slug: service.slug,
        categorySlug: service.categorySlug,
        titleAr: pageData.titleAr,
        titleEn: pageData.titleEn,
        categoryAr: pageData.categoryAr,
        categoryEn: pageData.categoryEn,
        shortDescAr: pageData.shortDescAr,
        shortDescEn: pageData.shortDescEn,
        aboutAr: pageData.aboutAr,
        aboutEn: pageData.aboutEn,
        features: pageData.features,
        processSteps: pageData.processSteps,
        useCases: pageData.useCases,
        faq: pageData.faq,
        published: true,
        order: index + 1,
      };
    })
    .sort((left, right) => left.order - right.order);

const seedHeroSlides = (): HeroSlideRecord[] => heroSlidesData.map((slide) => ({ ...slide }));

const seedSiteSettings = (): SiteSettingsRecord => ({
  id: 'main',
  logoImageUrl: '',
  logoImageAltAr: 'شعار شركة هشام حسن حنبولي الدولية',
  logoImageAltEn: 'Hesham H. Hanboly International logo',
  footerLogoImageUrl: '',
  footerLogoImageAltAr: 'شعار التذييل لشركة هشام حسن حنبولي الدولية',
  footerLogoImageAltEn: 'Hesham H. Hanboly International footer logo',
  navbarCtaAr: 'طلب استشارة',
  navbarCtaEn: 'Book Counsel',
  doctorShieldBadgeAr: 'جديد وحصري',
  doctorShieldBadgeEn: 'New & Exclusive',
  doctorShieldTitleAr: 'برنامج سند الطبيب الوقائي',
  doctorShieldTitleEn: 'Doctor Shield Protective Program',
  doctorShieldSubtitleAr: 'درعك القانوني وحمايتك القضائية الشاملة طوال العام الكلينيكي',
  doctorShieldSubtitleEn: 'Your ultimate legal companion throughout the practice year',
  doctorShieldDescAr: 'مشروع قانوني سنوي مبتكر مصمم خصيصاً للكوادر الطبية والممارسين الصحيين في المملكة العربية السعودية.',
  doctorShieldDescEn: 'A pioneering legal protective program custom-engineered for physicians and medical professionals in Saudi Arabia.',
  doctorShieldBullet1Ar: 'تمثيل قانوني وحضور التحقيقات بالنيابة عنك',
  doctorShieldBullet1En: 'Full representation and hearing attendance',
  doctorShieldBullet2Ar: 'دعم استشاري فوري وشبكة مخصصة ٢٤/٧',
  doctorShieldBullet2En: '24/7 priority emergency legal hotline',
  doctorShieldBullet3Ar: 'قيمة سنوية ثابتة وميسرة ٢٣٠٠ ريال فقط',
  doctorShieldBullet3En: 'Clear annual cost of only 2,300 SAR',
  doctorShieldBullet4Ar: 'شامل ضريبة القيمة المضافة بالكامل دون رسوم إضافية',
  doctorShieldBullet4En: 'VAT fully pre-included, no hidden filing fees',
  doctorShieldButtonAr: 'تفاصيل الخدمة والاشتراك الفوري',
  doctorShieldButtonEn: 'Explore Details & Register',
  doctorShieldCircleTitleAr: 'سند الطبيب',
  doctorShieldCircleTitleEn: 'Doctor Shield',
  doctorShieldCirclePriceAr: '٢٣٠٠ ريال / سنة',
  doctorShieldCirclePriceEn: '2,300 SAR / Yr',
  doctorShieldCircleNoteAr: 'شامل الضريبة',
  doctorShieldCircleNoteEn: 'VAT Included',
  aboutSectionBadgeAr: 'من نحن',
  aboutSectionBadgeEn: 'About Us',
  aboutSectionTitleAr: 'رواد حل النزاعات وحماية الاستثمارات بالمملكة والشرق الأوسط',
  aboutSectionTitleEn: 'Pioneers in Dispute Resolution & Asset Protection across the GCC',
  aboutSectionDescAr: 'تأسس مكتب هشام حسن حنبولي للمحاماة والاستشارات القانونية شريكاً موثوقاً وصاحب ريادة حثيثة في صيانة المصالح وتوفير الاستشارات المتكاملة للجهات والمجموعات الاستثمارية الرائدة.',
  aboutSectionDescEn: 'Hesham H. Hanboly Law Firm was established as a premier hub, and a trusted pioneer in defending valuable organizational assets and providing comprehensive legal consultations.',
  aboutSectionCardTitleAr: 'رعاية قضائية بمستوى نخبة الأعمال',
  aboutSectionCardTitleEn: 'Elite Enterprise Legal Guard',
  aboutSectionCardDescAr: 'عبر مسيرة متكاملة حافلة بالحلول القانونية، نضع رعاية شؤون الموكلين التجارية والتنظيمية في طليعة التزامنا.',
  aboutSectionCardDescEn: 'Through an extensive track record of legal solutions, we place our clients’ commercial and regulatory compliance at the absolute pinnacle of our values.',
  aboutSectionButtonAr: 'اطلب استشارتك الوقائية الفورية',
  aboutSectionButtonEn: 'Book Preventative Assessment Immediately',
  statisticsBadgeAr: 'إنجازات تدعو للفخر والاعتماد',
  statisticsBadgeEn: 'Proud track record of success',
  statisticsNumber: '+3000',
  statisticsTitleAr: 'عمل قانوني ناجح',
  statisticsTitleEn: 'Successful judicial operations',
  statisticsDescAr: 'هذه النتائج الاستثنائية هي ثمرة عمل كادر متناغم ومؤهل من أعضاء شركة هشام حسن حنبولي الدولية للاستشارات القانونية والمحاماة.',
  statisticsDescEn: 'These distinguished results are the fruit of collaborative, specialized legal performance by Hesham H. Hanboly International members.',
  statisticsSupportAr: 'تغطية قضائية متكاملة في المحاكم العامة، العمالية، والتجارية',
  statisticsSupportEn: 'Sovereign coverage in Supreme, Appellate, Labor, and Commercial tribunals',
  teamSectionBadgeAr: 'صناع القرار وعمود القوة القضائية',
  teamSectionBadgeEn: 'Judicial decision makers & leaders',
  teamSectionTitleAr: 'تعرف على مستشارينا القانونيين',
  teamSectionTitleEn: 'Meet our legal counsel',
  teamSectionDescAr: 'نخبة من الكفاءات القانونية التي تقود ملفات الدفاع وتوفر المشورة الرصينة للشركات والأفراد.',
  teamSectionDescEn: 'An elite league of legal practitioners spearheading advocacy and rendering bulletproof advisory for enterprises and individuals.',
  teamFounderBadgeAr: 'المؤسس والشريك المدير',
  teamFounderBadgeEn: 'Founder & Managing Partner',
  teamFounderNameAr: 'المحامي / هشام بن حسن حنبولي',
  teamFounderNameEn: 'Advocate / Hesham H. Hanboly',
  teamFounderRoleAr: 'مدير عام الشركة • مستشار قانوني ممارس',
  teamFounderRoleEn: 'Managing Director • Active Senior Legal Consultant',
  teamFounderIntroAr: 'يقود المستشار هشام بن حسن حنبولي أعمال الشركة بتوجيه استراتيجي متميز يجمع بين فهم الواقع الاقتصادي وصحيح الأحكام القضائية.',
  teamFounderIntroEn: 'Senior Counsel Hesham H. Hanboly leads the firm with a strategic, high-impact approach, bridging economic realities with regulatory environments.',
  teamFounderImageUrl: '/images/founder_hesham_hanboly_1780491593879.png',
  teamFounderImageAltAr: 'المحامي / هشام بن حسن حنبولي',
  teamFounderImageAltEn: 'Advocate / Hesham H. Hanboly',
  teamSectionCtaAr: 'تصفّح فريق العمل بالكامل',
  teamSectionCtaEn: 'Explore Full Team Members',
  contactSectionBadgeAr: 'نحن جاهزون لمساندتك بكفاءة مهنية مطلقة',
  contactSectionBadgeEn: 'We are ready to support you with supreme professionalism',
  contactSectionTitleAr: 'تواصل معنا',
  contactSectionTitleEn: 'Contact us',
  contactSectionDescAr: 'يسعدنا التوجيه والإجابة على كافة استفساراتكم القانونية بدقة وسرية تامة.',
  contactSectionDescEn: 'We are pleased to guide and answer all your legal inquiries with precision and utter confidentiality.',
  contactSectionOfficeTitleAr: 'مقر الإدارة والاتصال الموحد',
  contactSectionOfficeTitleEn: 'Headquarters & unified channels',
  contactSectionAddressHeadAr: 'المقر الرئيسي',
  contactSectionAddressHeadEn: 'Main headquarters',
  contactSectionPhoneLabelAr: 'الهاتف الموحد',
  contactSectionPhoneLabelEn: 'Unified number',
  contactSectionEmailLabelAr: 'البريد الرئيسي',
  contactSectionEmailLabelEn: 'Corporate email',
  contactSectionSecurityAr: '* كشريك مرخص ومقيد بوزارة العدل السعودية، تخضع كل رسالة ومكالمة لضمانة السرية المهنية.',
  contactSectionSecurityEn: '* As a licensed practice under the Saudi Ministry of Justice, all communications are fully guarded under professional confidentiality standards.',
  contactSectionFormTitleAr: 'تقديم استفسار قانوني آمن',
  contactSectionFormTitleEn: 'Submit a secure case assessment',
  contactSectionFormDescAr: 'أرسل استفسارك القانوني الآن وسيقوم مستشارنا القانوني بالرد والاتصال بكم.',
  contactSectionFormDescEn: 'Send us your legal inquiry now and one of our legal consultants will respond and contact you.',
  aboutHeroBadgeAr: 'من نحن',
  aboutHeroBadgeEn: 'About Us',
  aboutHeroTitleAr: 'شركة هشام حسن حنبولي الدولية',
  aboutHeroTitleEn: 'Hesham H. Hanboly International',
  aboutHeroDescAr: 'شركة هشام حسن حنبولي الدولية للاستشارات القانونية والمحاماة هي إحدى شركات المحاماة الكبرى في المملكة، وتضم نخبة من المحامين والمستشارين القانونيين ذوي الكفاءة والخبرة في مختلف التخصصات القانونية.',
  aboutHeroDescEn: 'Hesham H. Hanboly International Co. for Legal Consultations and Advocacy is a premier powerhouse law firm in the Kingdom, combining an elite group of highly specialized advocates and legal consultants.',
  teamHeroBadgeAr: 'فريقنا القضائي الموثوق',
  teamHeroBadgeEn: 'Our Trusted Judicial Alliance',
  teamHeroTitleAr: 'نخبة من المحامين والمستشارين القانونيين',
  teamHeroTitleEn: 'A Prestige League of Counselors & Attorneys',
  teamHeroDescAr: 'خبرات قانونية متخصصة تجمع بين الكفاءة العلمية والخبرة العملية لتقديم خدمات قانونية احترافية للأفراد والشركات، بأسمى غايات المصداقية والأمان القضائي.',
  teamHeroDescEn: 'Specialized legal expertise combining academic rigor and practical experience to deliver professional legal services for individuals and companies with the highest standards of trust and legal protection.',
  contactHeroBadgeAr: 'تواصل معنا',
  contactHeroBadgeEn: 'Contact Us',
  contactHeroTitleAr: 'خبراء قانونيون على استعداد لخدمتك',
  contactHeroTitleEn: 'Strategic Counselors Prepared to Defend',
  contactHeroDescAr: 'تواصل معنا للحصول على استشارات قانونية احترافية وخدمات قانونية متخصصة للأفراد والشركات في جميع أنحاء المملكة.',
  contactHeroDescEn: 'Reach out for refined legal consultations and bespoke representation, serving corporate players and prestigious individuals throughout the Kingdom.',
  footerDescriptionAr:
    'شركة هشام حسن حنبولي الدولية للاستشارات القانونية والمحاماة هي إحدى شركات المحاماة الرائدة في المملكة العربية السعودية، وحاصلة على تراخيص مزاولة المهنة والتمثيل القضائي من وزارة العدل بامتثال وقائي متكامل لحماية كيانات الاستثمار ومؤسسات التشييد والأعمال.',
  footerDescriptionEn:
    'Hesham H. Hanboly International Co. for Legal Consultations and Advocacy is a leading, specialized powerhouse law firm in Saudi Arabia, fully licensed by the Ministry of Justice for advocacy and judicial protection, providing elite corporate shield and preventative compliance for multinational enterprises.',
  addressAr: 'جدة - الروضة، شارع نهضة العلم',
  addressEn: 'Jeddah - Al-Rawdah, Nahdat Al-Elm Street',
  email: 'mec_law@hotmail.com',
  phone: '920004713',
  copyrightAr: '© ٢٠٢٦ شركة هشام حسن حنبولي الدولية للاستشارات القانونية والمحاماة. جميع الحقوق محفوظة.',
  copyrightEn: '© 2026 Hesham H. Hanboly International Law Co. All Rights Reserved.',
  footerBadgeAr: 'مكتب مرخص لمزاولة المحاماة بوزارة العدل بالمملكة العربية السعودية',
  footerBadgeEn: 'Licensed Practice for Advocacy & Defense by the Ministry of Justice, Saudi Arabia',
});

export const createSeedContent = (): SiteContent => ({
  heroSlides: seedHeroSlides(),
  articles: seedArticles(),
  practiceAreas: seedPracticeAreas(),
  navigation: [],
  siteSettings: seedSiteSettings(),
});
